name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      working-directory: ./server
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
